[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ChemoPar-db"
authors = [{name = "Bas de Boer", email = "b.de.boer2@vu.nl"}]
dynamic = ["version", "description"]
